# Generated by Django 3.0.5 on 2020-04-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200409_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='Profile',
        ),
    ]
