# Generated by Django 3.0.5 on 2020-04-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20200409_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile',
            new_name='user',
        ),
    ]
